overrides:
  cookie@<0.7.0: '>=0.7.0'
  devalue@<5.3.2: '>=5.3.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  vite@>=6.0.0 <=6.3.5: '>=6.3.6'
  vite@>=6.0.0 <=6.4.0: '>=6.4.1'
